// Auto-generated by generate_tokens.rb. DO NOT EDIT.
#ifndef TOKENS_HPP
#define TOKENS_HPP
enum class Token : int {
    PLUS = 258,
    MINUS = 259,
    STAR = 260,
    SLASH = 261,
    LPAREN = 262,
    RPAREN = 263,
    NUMBER = 264,
    VAR = 265,
    END_OF_FILE = 0,
};
#endif
