require_relative 'tokens_def'

def assign_values(tokens)
  value = 258
  tokens.map do |name, val|
    if val.nil?
      value += 1
      assigned = value
      [name, assigned]
    else
      [name, val]
    end
  end
end

TOKENS = assign_values(TOKENS_DEFINITION)

# Автоматически присваиваем значения, если nil
value = 258
TOKENS.each do |name, val|
  if val.nil?
    TOKENS.find { |n, v| n == name }[1] = value
    value += 1
  end
end

# ---------- Генерация tokens.h (C) ----------
File.open("src/tokens.h", "w") do |f|
  f.puts "// Auto-generated by generate_tokens.rb. DO NOT EDIT."
  f.puts "#ifndef TOKENS_H"
  f.puts "#define TOKENS_H\n"
  f.puts "enum {"
  TOKENS.each do |name, val|
    f.puts "    TOK_#{name} = #{val},"
  end
  f.puts "};\n"
  f.puts "#endif"
end

# ---------- Генерация tokens.hpp (C++) ----------
File.open("src/tokens.hpp", "w") do |f|
  f.puts "// Auto-generated by generate_tokens.rb. DO NOT EDIT."
  f.puts "#ifndef TOKENS_HPP"
  f.puts "#define TOKENS_HPP\n"
  f.puts "enum class Token : int {"
  TOKENS.each do |name, val|
    f.puts "    #{name} = #{val},"
  end
  f.puts "};\n"
  f.puts "#endif"
end

# ---------- Генерация token_utils.hpp ----------
File.open("src/token_utils.hpp", "w") do |f|
  f.puts "// Auto-generated by generate_tokens.rb. DO NOT EDIT."
  f.puts "#include \"tokens.hpp\""
  f.puts "#include <string>"
  f.puts
  f.puts "inline const char* token_name(Token tok) {"
  f.puts "    switch (tok) {"
  TOKENS.each do |name, _|
    next if name == :END_OF_FILE && TOKENS.last.first != :END_OF_FILE
    f.puts "        case Token::#{name}: return \"#{name}\";"
  end
  f.puts "        default: return \"UNKNOWN\";"
  f.puts "    }"
  f.puts "}"
end

puts "Generated tokens.h, tokens.hpp, token_utils.hpp"
