// Auto-generated by generate_tokens.rb. DO NOT EDIT.
#include "tokens.hpp"
#include <string>

inline const char* token_name(Token tok) {
    switch (tok) {
        case Token::PLUS: return "PLUS";
        case Token::MINUS: return "MINUS";
        case Token::STAR: return "STAR";
        case Token::SLASH: return "SLASH";
        case Token::LPAREN: return "LPAREN";
        case Token::RPAREN: return "RPAREN";
        case Token::NUMBER: return "NUMBER";
        case Token::VAR: return "VAR";
        case Token::END_OF_FILE: return "END_OF_FILE";
        default: return "UNKNOWN";
    }
}
