// Auto-generated by generate_tokens.rb. DO NOT EDIT.
#ifndef TOKENS_H
#define TOKENS_H
enum {
    TOK_PLUS = 258,
    TOK_MINUS = 259,
    TOK_STAR = 260,
    TOK_SLASH = 261,
    TOK_LPAREN = 262,
    TOK_RPAREN = 263,
    TOK_NUMBER = 264,
    TOK_VAR = 265,
    TOK_END_OF_FILE = 0,
};
#endif
